// Generated by vproto - Do not modify
module proto

import emily33901.vproto

pub struct CCommunity_GetLinkFilterHashPrefixes_Request {
mut:
	unknown_fields []vproto.UnknownField
pub mut:
	hit_type       u32
	has_hit_type   bool
	count          u32
	has_count      bool
	start          u64
	has_start      bool
}

pub fn (o &CCommunity_GetLinkFilterHashPrefixes_Request) pack() []byte {
	mut res := []byte{}
	if o.has_hit_type {
		res << vproto.pack_uint32_field(o.hit_type, 1)
	}
	if o.has_count {
		res << vproto.pack_uint32_field(o.count, 2)
	}
	if o.has_start {
		res << vproto.pack_uint64_field(o.start, 3)
	}
	return res
}

pub fn ccommunity_getlinkfilterhashprefixes_request_unpack(buf []byte) ?CCommunity_GetLinkFilterHashPrefixes_Request {
	mut res := CCommunity_GetLinkFilterHashPrefixes_Request{}
	mut total := 0
	for total < buf.len {
		mut i := 0
		buf_before_wire_type := buf[total..]
		tag_wiretype := vproto.unpack_tag_wire_type(buf_before_wire_type) or {
			return error('malformed protobuf (couldnt parse tag & wire type)')
		}
		cur_buf := buf_before_wire_type[tag_wiretype.consumed..]
		match tag_wiretype.tag {
			1 {
				res.has_hit_type = true
				ii, v := vproto.unpack_uint32_field(cur_buf, tag_wiretype.wire_type)?
				res.hit_type = v
				i = ii
			}
			2 {
				res.has_count = true
				ii, v := vproto.unpack_uint32_field(cur_buf, tag_wiretype.wire_type)?
				res.count = v
				i = ii
			}
			3 {
				res.has_start = true
				ii, v := vproto.unpack_uint64_field(cur_buf, tag_wiretype.wire_type)?
				res.start = v
				i = ii
			}
			else {
				ii, v := vproto.unpack_unknown_field(cur_buf, tag_wiretype.wire_type)
				res.unknown_fields <<
					vproto.UnknownField{tag_wiretype.wire_type, tag_wiretype.tag, v}
				i = ii
			}
		}
		if i == 0 {
			return error('malformed protobuf (didnt unpack a field)')
		}
		total += tag_wiretype.consumed + i
	}
	return res
}

// FOR INTERNAL USE ONLY
pub fn zzz_vproto_internal_new_ccommunity_getlinkfilterhashprefixes_request() CCommunity_GetLinkFilterHashPrefixes_Request {
	return CCommunity_GetLinkFilterHashPrefixes_Request{}
}

// FOR INTERNAL USE ONLY
pub fn zzz_vproto_internal_pack_ccommunity_getlinkfilterhashprefixes_request(o CCommunity_GetLinkFilterHashPrefixes_Request, num u32) []byte {
	return vproto.pack_message_field(o.pack(), num)
}

// FOR INTERNAL USE ONLY
pub fn zzz_vproto_internal_unpack_ccommunity_getlinkfilterhashprefixes_request(buf []byte, tag_wiretype vproto.WireType) ?(int, CCommunity_GetLinkFilterHashPrefixes_Request) {
	i, v := vproto.unpack_message_field(buf, tag_wiretype)?
	mut unpacked := ccommunity_getlinkfilterhashprefixes_request_unpack(v)?
	return i, unpacked
}

pub struct CCommunity_GetLinkFilterHashPrefixes_Response {
mut:
	unknown_fields []vproto.UnknownField
pub mut:
	hash_prefixes  []u32
}

pub fn (o &CCommunity_GetLinkFilterHashPrefixes_Response) pack() []byte {
	mut res := []byte{}
	// [packed=false]
	for _, x in o.hash_prefixes {
		res << vproto.pack_uint32_field(x, 1)
	}
	return res
}

pub fn ccommunity_getlinkfilterhashprefixes_response_unpack(buf []byte) ?CCommunity_GetLinkFilterHashPrefixes_Response {
	mut res := CCommunity_GetLinkFilterHashPrefixes_Response{}
	mut total := 0
	for total < buf.len {
		mut i := 0
		buf_before_wire_type := buf[total..]
		tag_wiretype := vproto.unpack_tag_wire_type(buf_before_wire_type) or {
			return error('malformed protobuf (couldnt parse tag & wire type)')
		}
		cur_buf := buf_before_wire_type[tag_wiretype.consumed..]
		match tag_wiretype.tag {
			1 {
				// [packed=false]
				ii, v := vproto.unpack_uint32_field(cur_buf, tag_wiretype.wire_type)?
				res.hash_prefixes << v
				i = ii
			}
			else {
				ii, v := vproto.unpack_unknown_field(cur_buf, tag_wiretype.wire_type)
				res.unknown_fields <<
					vproto.UnknownField{tag_wiretype.wire_type, tag_wiretype.tag, v}
				i = ii
			}
		}
		if i == 0 {
			return error('malformed protobuf (didnt unpack a field)')
		}
		total += tag_wiretype.consumed + i
	}
	return res
}

// FOR INTERNAL USE ONLY
pub fn zzz_vproto_internal_new_ccommunity_getlinkfilterhashprefixes_response() CCommunity_GetLinkFilterHashPrefixes_Response {
	return CCommunity_GetLinkFilterHashPrefixes_Response{}
}

// FOR INTERNAL USE ONLY
pub fn zzz_vproto_internal_pack_ccommunity_getlinkfilterhashprefixes_response(o CCommunity_GetLinkFilterHashPrefixes_Response, num u32) []byte {
	return vproto.pack_message_field(o.pack(), num)
}

// FOR INTERNAL USE ONLY
pub fn zzz_vproto_internal_unpack_ccommunity_getlinkfilterhashprefixes_response(buf []byte, tag_wiretype vproto.WireType) ?(int, CCommunity_GetLinkFilterHashPrefixes_Response) {
	i, v := vproto.unpack_message_field(buf, tag_wiretype)?
	mut unpacked := ccommunity_getlinkfilterhashprefixes_response_unpack(v)?
	return i, unpacked
}

pub struct CCommunity_GetLinkFilterHashes_Request {
mut:
	unknown_fields []vproto.UnknownField
pub mut:
	hit_type       u32
	has_hit_type   bool
	count          u32
	has_count      bool
	start          u64
	has_start      bool
}

pub fn (o &CCommunity_GetLinkFilterHashes_Request) pack() []byte {
	mut res := []byte{}
	if o.has_hit_type {
		res << vproto.pack_uint32_field(o.hit_type, 1)
	}
	if o.has_count {
		res << vproto.pack_uint32_field(o.count, 2)
	}
	if o.has_start {
		res << vproto.pack_uint64_field(o.start, 3)
	}
	return res
}

pub fn ccommunity_getlinkfilterhashes_request_unpack(buf []byte) ?CCommunity_GetLinkFilterHashes_Request {
	mut res := CCommunity_GetLinkFilterHashes_Request{}
	mut total := 0
	for total < buf.len {
		mut i := 0
		buf_before_wire_type := buf[total..]
		tag_wiretype := vproto.unpack_tag_wire_type(buf_before_wire_type) or {
			return error('malformed protobuf (couldnt parse tag & wire type)')
		}
		cur_buf := buf_before_wire_type[tag_wiretype.consumed..]
		match tag_wiretype.tag {
			1 {
				res.has_hit_type = true
				ii, v := vproto.unpack_uint32_field(cur_buf, tag_wiretype.wire_type)?
				res.hit_type = v
				i = ii
			}
			2 {
				res.has_count = true
				ii, v := vproto.unpack_uint32_field(cur_buf, tag_wiretype.wire_type)?
				res.count = v
				i = ii
			}
			3 {
				res.has_start = true
				ii, v := vproto.unpack_uint64_field(cur_buf, tag_wiretype.wire_type)?
				res.start = v
				i = ii
			}
			else {
				ii, v := vproto.unpack_unknown_field(cur_buf, tag_wiretype.wire_type)
				res.unknown_fields <<
					vproto.UnknownField{tag_wiretype.wire_type, tag_wiretype.tag, v}
				i = ii
			}
		}
		if i == 0 {
			return error('malformed protobuf (didnt unpack a field)')
		}
		total += tag_wiretype.consumed + i
	}
	return res
}

// FOR INTERNAL USE ONLY
pub fn zzz_vproto_internal_new_ccommunity_getlinkfilterhashes_request() CCommunity_GetLinkFilterHashes_Request {
	return CCommunity_GetLinkFilterHashes_Request{}
}

// FOR INTERNAL USE ONLY
pub fn zzz_vproto_internal_pack_ccommunity_getlinkfilterhashes_request(o CCommunity_GetLinkFilterHashes_Request, num u32) []byte {
	return vproto.pack_message_field(o.pack(), num)
}

// FOR INTERNAL USE ONLY
pub fn zzz_vproto_internal_unpack_ccommunity_getlinkfilterhashes_request(buf []byte, tag_wiretype vproto.WireType) ?(int, CCommunity_GetLinkFilterHashes_Request) {
	i, v := vproto.unpack_message_field(buf, tag_wiretype)?
	mut unpacked := ccommunity_getlinkfilterhashes_request_unpack(v)?
	return i, unpacked
}

pub struct CCommunity_GetLinkFilterHashes_Response {
mut:
	unknown_fields []vproto.UnknownField
pub mut:
	hashes         [][]byte
}

pub fn (o &CCommunity_GetLinkFilterHashes_Response) pack() []byte {
	mut res := []byte{}
	// [packed=false]
	for _, x in o.hashes {
		res << vproto.pack_bytes_field(x, 1)
	}
	return res
}

pub fn ccommunity_getlinkfilterhashes_response_unpack(buf []byte) ?CCommunity_GetLinkFilterHashes_Response {
	mut res := CCommunity_GetLinkFilterHashes_Response{}
	mut total := 0
	for total < buf.len {
		mut i := 0
		buf_before_wire_type := buf[total..]
		tag_wiretype := vproto.unpack_tag_wire_type(buf_before_wire_type) or {
			return error('malformed protobuf (couldnt parse tag & wire type)')
		}
		cur_buf := buf_before_wire_type[tag_wiretype.consumed..]
		match tag_wiretype.tag {
			1 {
				// [packed=false]
				ii, v := vproto.unpack_bytes_field(cur_buf, tag_wiretype.wire_type)?
				res.hashes << v
				i = ii
			}
			else {
				ii, v := vproto.unpack_unknown_field(cur_buf, tag_wiretype.wire_type)
				res.unknown_fields <<
					vproto.UnknownField{tag_wiretype.wire_type, tag_wiretype.tag, v}
				i = ii
			}
		}
		if i == 0 {
			return error('malformed protobuf (didnt unpack a field)')
		}
		total += tag_wiretype.consumed + i
	}
	return res
}

// FOR INTERNAL USE ONLY
pub fn zzz_vproto_internal_new_ccommunity_getlinkfilterhashes_response() CCommunity_GetLinkFilterHashes_Response {
	return CCommunity_GetLinkFilterHashes_Response{}
}

// FOR INTERNAL USE ONLY
pub fn zzz_vproto_internal_pack_ccommunity_getlinkfilterhashes_response(o CCommunity_GetLinkFilterHashes_Response, num u32) []byte {
	return vproto.pack_message_field(o.pack(), num)
}

// FOR INTERNAL USE ONLY
pub fn zzz_vproto_internal_unpack_ccommunity_getlinkfilterhashes_response(buf []byte, tag_wiretype vproto.WireType) ?(int, CCommunity_GetLinkFilterHashes_Response) {
	i, v := vproto.unpack_message_field(buf, tag_wiretype)?
	mut unpacked := ccommunity_getlinkfilterhashes_response_unpack(v)?
	return i, unpacked
}

pub struct CCommunity_GetLinkFilterListVersion_Request {
mut:
	unknown_fields []vproto.UnknownField
pub mut:
	hit_type       u32
	has_hit_type   bool
}

pub fn (o &CCommunity_GetLinkFilterListVersion_Request) pack() []byte {
	mut res := []byte{}
	if o.has_hit_type {
		res << vproto.pack_uint32_field(o.hit_type, 1)
	}
	return res
}

pub fn ccommunity_getlinkfilterlistversion_request_unpack(buf []byte) ?CCommunity_GetLinkFilterListVersion_Request {
	mut res := CCommunity_GetLinkFilterListVersion_Request{}
	mut total := 0
	for total < buf.len {
		mut i := 0
		buf_before_wire_type := buf[total..]
		tag_wiretype := vproto.unpack_tag_wire_type(buf_before_wire_type) or {
			return error('malformed protobuf (couldnt parse tag & wire type)')
		}
		cur_buf := buf_before_wire_type[tag_wiretype.consumed..]
		match tag_wiretype.tag {
			1 {
				res.has_hit_type = true
				ii, v := vproto.unpack_uint32_field(cur_buf, tag_wiretype.wire_type)?
				res.hit_type = v
				i = ii
			}
			else {
				ii, v := vproto.unpack_unknown_field(cur_buf, tag_wiretype.wire_type)
				res.unknown_fields <<
					vproto.UnknownField{tag_wiretype.wire_type, tag_wiretype.tag, v}
				i = ii
			}
		}
		if i == 0 {
			return error('malformed protobuf (didnt unpack a field)')
		}
		total += tag_wiretype.consumed + i
	}
	return res
}

// FOR INTERNAL USE ONLY
pub fn zzz_vproto_internal_new_ccommunity_getlinkfilterlistversion_request() CCommunity_GetLinkFilterListVersion_Request {
	return CCommunity_GetLinkFilterListVersion_Request{}
}

// FOR INTERNAL USE ONLY
pub fn zzz_vproto_internal_pack_ccommunity_getlinkfilterlistversion_request(o CCommunity_GetLinkFilterListVersion_Request, num u32) []byte {
	return vproto.pack_message_field(o.pack(), num)
}

// FOR INTERNAL USE ONLY
pub fn zzz_vproto_internal_unpack_ccommunity_getlinkfilterlistversion_request(buf []byte, tag_wiretype vproto.WireType) ?(int, CCommunity_GetLinkFilterListVersion_Request) {
	i, v := vproto.unpack_message_field(buf, tag_wiretype)?
	mut unpacked := ccommunity_getlinkfilterlistversion_request_unpack(v)?
	return i, unpacked
}

pub struct CCommunity_GetLinkFilterListVersion_Response {
mut:
	unknown_fields []vproto.UnknownField
pub mut:
	version        string
	has_version    bool
	count          u64
	has_count      bool
}

pub fn (o &CCommunity_GetLinkFilterListVersion_Response) pack() []byte {
	mut res := []byte{}
	if o.has_version {
		res << vproto.pack_string_field(o.version, 1)
	}
	if o.has_count {
		res << vproto.pack_uint64_field(o.count, 2)
	}
	return res
}

pub fn ccommunity_getlinkfilterlistversion_response_unpack(buf []byte) ?CCommunity_GetLinkFilterListVersion_Response {
	mut res := CCommunity_GetLinkFilterListVersion_Response{}
	mut total := 0
	for total < buf.len {
		mut i := 0
		buf_before_wire_type := buf[total..]
		tag_wiretype := vproto.unpack_tag_wire_type(buf_before_wire_type) or {
			return error('malformed protobuf (couldnt parse tag & wire type)')
		}
		cur_buf := buf_before_wire_type[tag_wiretype.consumed..]
		match tag_wiretype.tag {
			1 {
				res.has_version = true
				ii, v := vproto.unpack_string_field(cur_buf, tag_wiretype.wire_type)?
				res.version = v
				i = ii
			}
			2 {
				res.has_count = true
				ii, v := vproto.unpack_uint64_field(cur_buf, tag_wiretype.wire_type)?
				res.count = v
				i = ii
			}
			else {
				ii, v := vproto.unpack_unknown_field(cur_buf, tag_wiretype.wire_type)
				res.unknown_fields <<
					vproto.UnknownField{tag_wiretype.wire_type, tag_wiretype.tag, v}
				i = ii
			}
		}
		if i == 0 {
			return error('malformed protobuf (didnt unpack a field)')
		}
		total += tag_wiretype.consumed + i
	}
	return res
}

// FOR INTERNAL USE ONLY
pub fn zzz_vproto_internal_new_ccommunity_getlinkfilterlistversion_response() CCommunity_GetLinkFilterListVersion_Response {
	return CCommunity_GetLinkFilterListVersion_Response{}
}

// FOR INTERNAL USE ONLY
pub fn zzz_vproto_internal_pack_ccommunity_getlinkfilterlistversion_response(o CCommunity_GetLinkFilterListVersion_Response, num u32) []byte {
	return vproto.pack_message_field(o.pack(), num)
}

// FOR INTERNAL USE ONLY
pub fn zzz_vproto_internal_unpack_ccommunity_getlinkfilterlistversion_response(buf []byte, tag_wiretype vproto.WireType) ?(int, CCommunity_GetLinkFilterListVersion_Response) {
	i, v := vproto.unpack_message_field(buf, tag_wiretype)?
	mut unpacked := ccommunity_getlinkfilterlistversion_response_unpack(v)?
	return i, unpacked
}
